
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIV ID MAS MENOS PARD PARI PORstart : exp_eexp_e    : exp_e MAS exp_t\n                | exp_e MENOS exp_texp_e : exp_texp_t    : exp_t POR exp_f\n                | exp_t DIV exp_fexp_t : exp_fexp_f : PARI exp_e PARDexp_f : ID'
    
_lr_action_items = {'PARI':([0,5,7,8,9,10,],[5,5,5,5,5,5,]),'ID':([0,5,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,6,12,13,14,15,16,],[0,-1,-4,-7,-9,-2,-3,-5,-6,-8,]),'MAS':([2,3,4,6,11,12,13,14,15,16,],[7,-4,-7,-9,7,-2,-3,-5,-6,-8,]),'MENOS':([2,3,4,6,11,12,13,14,15,16,],[8,-4,-7,-9,8,-2,-3,-5,-6,-8,]),'PARD':([3,4,6,11,12,13,14,15,16,],[-4,-7,-9,16,-2,-3,-5,-6,-8,]),'POR':([3,4,6,12,13,14,15,16,],[9,-7,-9,9,9,-5,-6,-8,]),'DIV':([3,4,6,12,13,14,15,16,],[10,-7,-9,10,10,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'exp_e':([0,5,],[2,11,]),'exp_t':([0,5,7,8,],[3,3,12,13,]),'exp_f':([0,5,7,8,9,10,],[4,4,4,4,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> exp_e','start',1,'p_start','gramatica.py',49),
  ('exp_e -> exp_e MAS exp_t','exp_e',3,'p_adicion','gramatica.py',53),
  ('exp_e -> exp_e MENOS exp_t','exp_e',3,'p_adicion','gramatica.py',54),
  ('exp_e -> exp_t','exp_e',1,'p_to_multiplo','gramatica.py',65),
  ('exp_t -> exp_t POR exp_f','exp_t',3,'p_multiplicacion','gramatica.py',69),
  ('exp_t -> exp_t DIV exp_f','exp_t',3,'p_multiplicacion','gramatica.py',70),
  ('exp_t -> exp_f','exp_t',1,'p_to_f','gramatica.py',81),
  ('exp_f -> PARI exp_e PARD','exp_f',3,'p_parentesis','gramatica.py',85),
  ('exp_f -> ID','exp_f',1,'p_soloid','gramatica.py',89),
]
