
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIGUALNOIGUALMENORMAYORMENORIGUALMAYORIGUALleftORleftANDRIGHTNOTAND DIV ID IGUAL MAS MAYOR MAYORIGUAL MENOR MENORIGUAL MENOS NOIGUAL NOT OR PARD PARI PORstart : exp_lexp_l    : exp_l AND exp_r\n                | exp_l OR exp_rexp_l : NOT exp_rexp_l : exp_rexp_r    : exp_e MENOR exp_e\n                | exp_e MENORIGUAL exp_e\n                | exp_e MAYOR exp_e\n                | exp_e MAYORIGUAL exp_e\n                | exp_e IGUAL exp_e\n                | exp_e NOIGUAL exp_eexp_r : exp_eexp_e    : exp_e MAS exp_t\n                | exp_e MENOS exp_texp_e : exp_texp_t    : exp_t POR exp_f\n                | exp_t DIV exp_fexp_t : exp_fexp_f : PARI exp_e PARDexp_f : ID'
    
_lr_action_items = {'NOT':([0,],[4,]),'PARI':([0,4,8,10,11,13,14,15,16,17,18,19,20,21,22,],[8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'ID':([0,4,8,10,11,13,14,15,16,17,18,19,20,21,22,],[9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,]),'$end':([1,2,3,5,6,7,9,12,24,25,26,27,28,29,30,31,32,33,34,35,36,],[0,-1,-5,-12,-15,-18,-20,-4,-2,-3,-6,-7,-8,-9,-10,-11,-13,-14,-16,-17,-19,]),'AND':([2,3,5,6,7,9,12,24,25,26,27,28,29,30,31,32,33,34,35,36,],[10,-5,-12,-15,-18,-20,-4,-2,-3,-6,-7,-8,-9,-10,-11,-13,-14,-16,-17,-19,]),'OR':([2,3,5,6,7,9,12,24,25,26,27,28,29,30,31,32,33,34,35,36,],[11,-5,-12,-15,-18,-20,-4,-2,-3,-6,-7,-8,-9,-10,-11,-13,-14,-16,-17,-19,]),'MENOR':([5,6,7,9,32,33,34,35,36,],[13,-15,-18,-20,-13,-14,-16,-17,-19,]),'MENORIGUAL':([5,6,7,9,32,33,34,35,36,],[14,-15,-18,-20,-13,-14,-16,-17,-19,]),'MAYOR':([5,6,7,9,32,33,34,35,36,],[15,-15,-18,-20,-13,-14,-16,-17,-19,]),'MAYORIGUAL':([5,6,7,9,32,33,34,35,36,],[16,-15,-18,-20,-13,-14,-16,-17,-19,]),'IGUAL':([5,6,7,9,32,33,34,35,36,],[17,-15,-18,-20,-13,-14,-16,-17,-19,]),'NOIGUAL':([5,6,7,9,32,33,34,35,36,],[18,-15,-18,-20,-13,-14,-16,-17,-19,]),'MAS':([5,6,7,9,23,26,27,28,29,30,31,32,33,34,35,36,],[19,-15,-18,-20,19,19,19,19,19,19,19,-13,-14,-16,-17,-19,]),'MENOS':([5,6,7,9,23,26,27,28,29,30,31,32,33,34,35,36,],[20,-15,-18,-20,20,20,20,20,20,20,20,-13,-14,-16,-17,-19,]),'PARD':([6,7,9,23,32,33,34,35,36,],[-15,-18,-20,36,-13,-14,-16,-17,-19,]),'POR':([6,7,9,32,33,34,35,36,],[21,-18,-20,21,21,-16,-17,-19,]),'DIV':([6,7,9,32,33,34,35,36,],[22,-18,-20,22,22,-16,-17,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'exp_l':([0,],[2,]),'exp_r':([0,4,10,11,],[3,12,24,25,]),'exp_e':([0,4,8,10,11,13,14,15,16,17,18,],[5,5,23,5,5,26,27,28,29,30,31,]),'exp_t':([0,4,8,10,11,13,14,15,16,17,18,19,20,],[6,6,6,6,6,6,6,6,6,6,6,32,33,]),'exp_f':([0,4,8,10,11,13,14,15,16,17,18,19,20,21,22,],[7,7,7,7,7,7,7,7,7,7,7,7,7,34,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> exp_l','start',1,'p_start','gramatica.py',80),
  ('exp_l -> exp_l AND exp_r','exp_l',3,'p_logic','gramatica.py',84),
  ('exp_l -> exp_l OR exp_r','exp_l',3,'p_logic','gramatica.py',85),
  ('exp_l -> NOT exp_r','exp_l',2,'p_logic_not','gramatica.py',106),
  ('exp_l -> exp_r','exp_l',1,'p_logic_rel','gramatica.py',113),
  ('exp_r -> exp_e MENOR exp_e','exp_r',3,'p_rel','gramatica.py',117),
  ('exp_r -> exp_e MENORIGUAL exp_e','exp_r',3,'p_rel','gramatica.py',118),
  ('exp_r -> exp_e MAYOR exp_e','exp_r',3,'p_rel','gramatica.py',119),
  ('exp_r -> exp_e MAYORIGUAL exp_e','exp_r',3,'p_rel','gramatica.py',120),
  ('exp_r -> exp_e IGUAL exp_e','exp_r',3,'p_rel','gramatica.py',121),
  ('exp_r -> exp_e NOIGUAL exp_e','exp_r',3,'p_rel','gramatica.py',122),
  ('exp_r -> exp_e','exp_r',1,'p_rel_e','gramatica.py',149),
  ('exp_e -> exp_e MAS exp_t','exp_e',3,'p_adicion','gramatica.py',153),
  ('exp_e -> exp_e MENOS exp_t','exp_e',3,'p_adicion','gramatica.py',154),
  ('exp_e -> exp_t','exp_e',1,'p_to_multiplo','gramatica.py',165),
  ('exp_t -> exp_t POR exp_f','exp_t',3,'p_multiplicacion','gramatica.py',169),
  ('exp_t -> exp_t DIV exp_f','exp_t',3,'p_multiplicacion','gramatica.py',170),
  ('exp_t -> exp_f','exp_t',1,'p_to_f','gramatica.py',181),
  ('exp_f -> PARI exp_e PARD','exp_f',3,'p_parentesis','gramatica.py',185),
  ('exp_f -> ID','exp_f',1,'p_soloid','gramatica.py',189),
]
